---
# roles/dependencies/handlers/main.yml
# Handlers for the dependencies role

- name: reboot_if_required
  reboot:
    msg: "System packages updated. Rebooting..."
    pre_reboot_delay: 5
    post_reboot_delay: 30
    test_command: /usr/bin/systemctl
  listen: reboot_if_required
